backend:
  name: github
  repo: anton-fichte/bio-praeparate
  branch: main
  api_root: https://decap-password-auth.anton-stuetzle.workers.dev/api/v3

media_folder: "bilder"
public_folder: "/bilder"

collections:
  - name: "praeparate"
    label: "Präparate"
    folder: "praeparate" # Ordner im Repo, in dem die einzelnen JSON-Dateien gespeichert werden
    create: true
    slug: "{{id}}" # Der Dateiname entspricht der ID (z.B. praeparate/101.json)
    extension: "json"
    format: "json"
    summary: '{{id}} - {{name}} ({{ort}})'
    fields:
      - { label: "ID", name: "id", widget: "string", pattern: ['^[a-zA-Z0-9_-]+$', 'Die ID darf nur Buchstaben (ohne Umlaute), Zahlen, Bindestriche und Unterstriche enthalten!'] }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Standort", name: "ort", widget: "string" }
      - { label: "Stichwörter/Tags", name: "stichwoerter", widget: "list", required: false, default: [] }
      - { label: "Bild", name: "bild", widget: "image", required: false }
