backend:
  name: git-gateway
  branch: main # oder master, je nach Repository

media_folder: "images"
public_folder: "/images"

collections:
  - name: "praeparate_collection"
    label: "Präparate"
    files:
      - file: "daten.json"
        label: "Präparate Liste"
        name: "praeparate_file"
        fields:
          - label: "Präparate"
            name: "praeparate"
            widget: "list"
            # WICHTIG: Zeigt Name & Ort im Admin-Kasten an, damit das Suchfeld beides durchsuchen kann!
            summary: '{{fields.praeparat.name}} ({{fields.praeparat.ort}})'
            fields:
              - label: "Präparat"
                name: "praeparat"
                widget: "object"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Standort", name: "ort", widget: "string" }
                  - label: "Stichwörter/Tags"
                    name: "stichwoerter"
                    widget: "list"
                    required: false
                    default: []
                  - { label: "Bild", name: "bild", widget: "image", required: false }
