backend:
  name: git-gateway
  branch: main # oder master, je nach Repository

# Bilder-Ordner im Repository und auf der Website
media_folder: "bilder"
public_folder: "/bilder"

collections:
  - name: "praeparate_collection"
    label: "Präparate"
    files:
      - file: "daten.json"
        label: "Präparate Liste"
        name: "praeparate_file"
        fields:
          - label: "Präparate"
            name: "praeparate"
            widget: "list"
            summary: '{{fields.praeparat.id}} - {{fields.praeparat.name}} ({{fields.praeparat.ort}})'
            fields:
              - label: "Präparat"
                name: "praeparat"
                widget: "object"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Standort", name: "ort", widget: "string" }
                  - label: "Stichwörter/Tags"
                    name: "stichwoerter"
                    widget: "list"
                    required: false
                    default: []
                  - { label: "Bild", name: "bild", widget: "image", required: false }
